// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr9DlrwKZslULXhnhxrz6m-9jXSyRaMEs',
    appId: '1:671475635999:web:4935543195d2a2f7aa022a',
    messagingSenderId: '671475635999',
    projectId: 'mega-app-50d1a',
    authDomain: 'mega-app-50d1a.firebaseapp.com',
    storageBucket: 'mega-app-50d1a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_your_android_api_key_here',
    appId: '1:your_sender_id:android:your_android_app_id',
    messagingSenderId: 'your_sender_id_here',
    projectId: 'mega-app-50d1a',
    storageBucket: 'mega-app-50d1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_your_ios_api_key_here',
    appId: '1:your_sender_id:ios:your_ios_app_id',
    messagingSenderId: 'your_sender_id_here',
    projectId: 'mega-app-50d1a',
    storageBucket: 'mega-app-50d1a.appspot.com',
    iosBundleId: 'com.example.megaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_your_macos_api_key_here',
    appId: '1:your_sender_id:macos:your_macos_app_id',
    messagingSenderId: 'your_sender_id_here',
    projectId: 'mega-app-50d1a',
    storageBucket: 'mega-app-50d1a.appspot.com',
    iosBundleId: 'com.example.megaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_your_windows_api_key_here',
    appId: '1:your_sender_id:web:your_windows_app_id',
    messagingSenderId: 'your_sender_id_here',
    projectId: 'mega-app-50d1a',
    authDomain: 'mega-app-50d1a.firebaseapp.com',
    storageBucket: 'mega-app-50d1a.appspot.com',
  );
}